
version: '3'
services:
    config:
        build:
            context: ../ConfigServer
        ports:
            - "8888:8888"
        volumes:
            - ../ConfigServer:/app
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    mo:
        build:
            context: ../middleOffice
        ports:
            - "8080:8080"
        depends_on:
            - config
        volumes:
            - ../middleOffice:/app
        environment:
            - CONFIG_SERVER_URL=config:8888
            - KC_HOST=host.docker.internal:8083
            - SPRING_PROFILES_ACTIVE=docker
        command:
             /bin/bash -c "sleep 5 && java -jar /app.jar"

    referential:
        build:
            context: ../referential
        ports:
            - "8081:8081"
        depends_on:
            - config
        volumes:
            - ../referential:/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - CONFIG_SERVER_URL=config:8888
            - DB_HOST=host.docker.internal
            - DB_USERNAME=referentialuser
            - DB_PASSWORD=Tristan2006!
            - SPRING_PROFILES_ACTIVE=docker
        command:
             /bin/bash -c "sleep 5 && java -jar /app.jar"

    nginx:
        build:
            context: ../nginx
        ports:
            - "80:80"
        depends_on:
            - mo
            - referential
        environment:
            - api=mo
            - referential=referential
            - config=config
            - auth=host.docker.internal